[package]
name = "k-engine-app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k-engine-core = { path = "../k-engine-core" }
k-engine-macros = { path = "../k-engine-macros" }
